=== fire-uta/ir-simulation/example-config/qsdl-0.1.xsd
<?xml version="1.0"?>
<xs:schema
 targetNamespace="urn:X-fi-uta-sis-fire:qsdl"
 xmlns:qsdl="urn:X-fi-uta-sis-fire:qsdl"
 xmlns:xs="http://www.w3.org/2001/XMLSchema" >

 <xs:complexType name="qsdl">
  <xs:all>
   <xs:element name="actions" type="qsdl:actions" form="qualified" />
   <xs:element name="costs" type="qsdl:costs" form="qualified" />
   <xs:element name="gains" type="qsdl:gains" form="qualified" />
   <xs:element name="decays" type="qsdl:decays" form="qualified" minOccurs="0" />
   <xs:element name="transitions" type="qsdl:trans" form="qualified" />
   <xs:element name="probabilities" type="qsdl:probabilities" form="qualified" />
   <xs:element name="probability-conditions" type="qsdl:probability-conditions" form="qualified" minOccurs="0" />
  </xs:all>
 </xs:complexType>

 <!-- Root element -->
 <xs:element name="qsdl" type="qsdl:qsdl">

  <!-- KEYS: -->

  <xs:key name="action-id">
   <xs:selector xpath="qsdl:actions/qsdl:action" />
   <xs:field xpath="@id" />
  </xs:key>

  <xs:key name="cost-id">
   <xs:selector xpath="qsdl:costs/qsdl:cost" />
   <xs:field xpath="@id" />
  </xs:key>

  <xs:key name="gain-id">
   <xs:selector xpath="qsdl:gains/qsdl:gain" />
   <xs:field xpath="@id" />
  </xs:key>

  <xs:key name="decay-id">
   <xs:selector xpath="qsdl:decays/qsdl:decay" />
   <xs:field xpath="@id" />
  </xs:key>

  <xs:key name="probability-id">
   <xs:selector xpath="qsdl:probabilities/qsdl:probability" />
   <xs:field xpath="@id" />
  </xs:key>

  <xs:key name="condition-id">
   <xs:selector xpath="qsdl:probability-conditions/qsdl:probability-condition" />
   <xs:field xpath="@id" />
  </xs:key>

  <!-- KEY REFERENCES: -->

  <xs:keyref name="cost-reference" refer="qsdl:cost-id">
   <xs:selector xpath="qsdl:actions/qsdl:action" />
   <xs:field xpath="@cost" />
  </xs:keyref>

  <xs:keyref name="gain-reference" refer="qsdl:gain-id">
   <xs:selector xpath="qsdl:actions/qsdl:action" />
   <xs:field xpath="@gain" />
  </xs:keyref>

  <xs:keyref name="decay-reference" refer="qsdl:decay-id">
   <xs:selector xpath="qsdl:transitions/qsdl:from/qsdl:to" />
   <xs:field xpath="@decay" />
  </xs:keyref>

  <xs:keyref name="source-action-reference" refer="qsdl:action-id">
   <xs:selector xpath="qsdl:transitions/qsdl:from" />
   <xs:field xpath="@source" />
  </xs:keyref>
  <xs:keyref name="target-action-reference" refer="qsdl:action-id">
   <xs:selector xpath="qsdl:transitions/qsdl:from/qsdl:to" />
   <xs:field xpath="@target" />
  </xs:keyref>
  <xs:keyref name="probability-reference" refer="qsdl:probability-id">
   <xs:selector xpath="qsdl:transitions/qsdl:from/qsdl:to" />
   <xs:field xpath="@probability" />
  </xs:keyref>

  <xs:keyref name="if-condition-reference" refer="qsdl:condition-id">
   <xs:selector xpath="qsdl:probabilities/qsdl:probability/qsdl:if" />
   <xs:field xpath="@condition" />
  </xs:keyref>
  <xs:keyref name="else-if-condition-reference" refer="qsdl:condition-id">
   <xs:selector xpath="qsdl:probabilities/qsdl:probability/qsdl:else-if" />
   <xs:field xpath="@condition" />
  </xs:keyref>

 </xs:element>

 <!-- Actions element -->
 <xs:complexType name="actions">
  <xs:sequence>
   <xs:element name="action" minOccurs="1" maxOccurs="unbounded" form="qualified" >
    <xs:complexType>
     <xs:sequence>
      <xs:element name="trigger" minOccurs="0" maxOccurs="unbounded" form="qualified">
       <xs:complexType>
        <xs:sequence>
         <xs:element name="argument" minOccurs="0" maxOccurs="unbounded" form="qualified">
          <xs:complexType>
           <xs:attribute name="name" type="xs:string" use="required" />
           <xs:attribute name="value" type="xs:string" use="required" />
          </xs:complexType>
         </xs:element>
        </xs:sequence>
        <xs:attribute name="type" type="xs:string" use="required" />
       </xs:complexType>
      </xs:element>
     </xs:sequence>
     <xs:attribute name="id" type="xs:string" use="required" />
     <xs:attribute name="cost" type="xs:string" use="optional" />
     <xs:attribute name="gain" type="xs:string" use="optional" />
     <xs:attribute name="final" type="xs:boolean" use="optional" default="false" />
    </xs:complexType>
   </xs:element>
  </xs:sequence>
  <xs:attribute name="initial" type="xs:string" use="required" />
 </xs:complexType>

 <!-- Callback or value type (for gains and costs) -->
 <xs:complexType name="callback-or-value">
  <xs:choice>
   <xs:element name="callback" type="qsdl:callback-with-arguments" form="qualified"/>
   <xs:element name="value" type="xs:decimal" form="qualified" />
  </xs:choice>
  <xs:attribute name="id" type="xs:string" use="required" />
 </xs:complexType>

 <!-- Callback type (for probability conditions) -->
 <xs:complexType name="callback">
  <xs:sequence>
   <xs:element name="callback" type="qsdl:callback-with-arguments" minOccurs="1" maxOccurs="1" form="qualified" />
  </xs:sequence>
  <xs:attribute name="id" type="xs:string" use="required" />
 </xs:complexType>

 <!-- Inner callback element type -->
 <xs:complexType name="callback-with-arguments">
  <xs:sequence>
   <xs:element name="argument" minOccurs="0" maxOccurs="unbounded" form="qualified">
    <xs:complexType>
     <xs:attribute name="name" use="required" type="xs:string" />
     <xs:attribute name="value" use="required" type="qsdl:callback-argument-value" />
    </xs:complexType>
   </xs:element>
  </xs:sequence>
  <xs:attribute name="name" use="required" type="xs:string" />
 </xs:complexType>

 <xs:simpleType name="callback-argument-value">
  <xs:union memberTypes="qsdl:callback-argument-value-non-variable qsdl:probability-value-variable" />
 </xs:simpleType>

 <!-- TODO: move to external file, since this is used in both config and qsdl -->
 <xs:simpleType name="callback-argument-value-non-variable">
  <xs:restriction base="xs:string">
   <xs:pattern value="[^$].*" />
  </xs:restriction>
 </xs:simpleType>

 <!-- Costs element type -->
 <xs:complexType name="costs">
  <xs:sequence>
   <xs:element name="cost" minOccurs="1" maxOccurs="unbounded" form="qualified" type="qsdl:callback-or-value" />
  </xs:sequence>
 </xs:complexType>

 <!-- Gains element type -->
 <xs:complexType name="gains">
  <xs:sequence>
   <xs:element name="gain" minOccurs="1" maxOccurs="unbounded" form="qualified" type="qsdl:callback-or-value" />
  </xs:sequence>
 </xs:complexType>

 <!-- Decays element type -->
 <xs:complexType name="decays">
  <xs:sequence>
   <xs:element name="decay" minOccurs="1" maxOccurs="unbounded" form="qualified" type="qsdl:callback" />
  </xs:sequence>
 </xs:complexType>

 <!-- Transitions element -->
 <xs:complexType name="trans">
  <xs:sequence>
   <xs:element name="from" minOccurs="1" maxOccurs="unbounded" form="qualified">
    <xs:complexType>
     <xs:sequence>
      <xs:element name="to" minOccurs="1" maxOccurs="unbounded" form="qualified">
       <xs:complexType>
        <xs:attribute name="target" type="xs:string" use="required" />
        <xs:attribute name="probability" type="xs:string" use="required" />
        <xs:attribute name="decay-effect" type="qsdl:decay-effect" use="optional" default="=" />
       </xs:complexType>
      </xs:element>
     </xs:sequence>
     <xs:attribute name="source" type="xs:string" use="required" />
     <xs:attribute name="decay" type="xs:string" use="optional" />
    </xs:complexType>
   </xs:element>
  </xs:sequence>
 </xs:complexType>

 <!-- Probabilities element -->
 <xs:complexType name="probabilities">
  <xs:sequence>
   <xs:element name="probability" minOccurs="1" maxOccurs="unbounded" form="qualified">
    <xs:complexType>
     <xs:choice>
      <xs:sequence>
       <xs:element name="if" form="qualified">
        <xs:complexType>
         <xs:attribute name="condition" type="xs:string" use="required" />
         <xs:attribute name="negation" type="xs:boolean" use="optional" default="false"/>
         <xs:attribute name="value" type="qsdl:probability-value" use="required" />
        </xs:complexType>
       </xs:element>
       <xs:element name="else-if" minOccurs="0" maxOccurs="unbounded" form="qualified">
        <xs:complexType>
         <xs:attribute name="condition" type="xs:string" use="required" />
         <xs:attribute name="negation" type="xs:boolean" use="optional" default="false"/>
         <xs:attribute name="value" type="qsdl:probability-value" use="required" />
        </xs:complexType>
       </xs:element>
       <xs:element name="else" form="qualified">
        <xs:complexType>
         <xs:attribute name="value" type="qsdl:probability-value" use="required" />
        </xs:complexType>
       </xs:element>
      </xs:sequence>
      <xs:element name="callback" type="qsdl:callback-with-arguments" form="qualified" />
      <xs:element name="value" type="qsdl:probability-value" form="qualified" />
     </xs:choice>
     <xs:attribute name="id" type="xs:string" use="required" />
    </xs:complexType>
   </xs:element>
  </xs:sequence>
 </xs:complexType>

 <!-- Probability conditions element type -->
 <xs:complexType name="probability-conditions">
  <xs:sequence>
   <xs:element name="probability-condition" minOccurs="1" maxOccurs="unbounded" form="qualified" type="qsdl:callback" />
  </xs:sequence>
 </xs:complexType>

 <!-- Probability value can be a decimal number between 0 and 1;
 An asterisk (*) is a special value that means the probability will be
 calculated at run-time. -->
 <xs:simpleType name="probability-value" id="PROB_VAL">
  <xs:union memberTypes="qsdl:probability-value-direct qsdl:probability-value-calculated qsdl:probability-value-variable" />
 </xs:simpleType>

 <!-- TODO: move to external file, since this is used in both config and qsdl -->
 <xs:simpleType name="probability-value-direct">
  <xs:restriction base="xs:decimal">
   <xs:minInclusive value="0.0" />
   <xs:maxInclusive value="1.0" />
  </xs:restriction>
 </xs:simpleType>

 <xs:simpleType name="probability-value-calculated">
  <xs:restriction base="xs:string">
   <xs:enumeration value="*" />
  </xs:restriction>
 </xs:simpleType>

 <!-- TODO: move to external file, since this is used in both config and qsdl -->
 <xs:simpleType name="probability-value-variable">
  <xs:restriction base="xs:string">
   <xs:pattern value="$[A-Za-z0-9]+" />
  </xs:restriction>
 </xs:simpleType>

 <xs:simpleType name="decay-effect">
  <xs:restriction base="xs:string">
   <xs:enumeration value="+" />
   <xs:enumeration value="-" />
   <xs:enumeration value="=" />
  </xs:restriction>
 </xs:simpleType>

</xs:schema>

=== fire-uta/ir-simulation/example-config/simulation.xml
<?xml version="1.0"?>
<qsdl xmlns="urn:X-fi-uta-sis-fire:qsdl"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="urn:X-fi-uta-sis-fire:qsdl qsdl-0.1.xsd">
 <actions initial="query_first">

  <!-- First query in session -->
  <action id="query_first" cost="current_query">
   <trigger type="jumpToQuery">
    <argument name="qidx" value="0" />
   </trigger>
  </action>

  <!-- Go to next query -->
  <action id="next_query" cost="current_query">
   <trigger type="nextQuery" />
  </action>

  <!-- Scan a summary -->
  <action id="scan_one_summary" cost="scan_one_summary">
   <trigger type="nextDocument" />
   <!-- <trigger type="dummy" />  -->
  </action>
  
  <!-- Read a whole document to judge its relevance -->
  <action id="read_document" cost="read_document">
   <trigger type="flagAsSeen" />
  </action>

  <!-- Skip to the next page of query results -->
  <action id="turn_page" cost="turn_page" />
  
  <!-- Judge document as relevant -->
  <action id="judge_as_relevant" gain="current_document" />
   
   <!-- End of simulation. (It is possible to have several ends) -->
  <action id="give_up" final="true" />
  <action id="natural_end" final="true" />
  <action id="stop_at_max_rank" final="true" />
  
 </actions>
 
 <costs>
  <cost id="current_query">
   <callback name="get_default_current_query_cost">
    <argument name="key_cost" value="0.28" />
   </callback>
  </cost>
  <!-- 
  <cost id="dummy">
   <callback name="dummy" />
  </cost>
   -->
  <cost id="scan_one_summary">
   <value>19</value>
  </cost>
  <cost id="read_document">
   <value>90</value>
  </cost>
  <cost id="turn_page">
   <value>2</value>
  </cost>
 </costs>
 
 <gains>
  <gain id="current_document">
   <callback name="get_current_document_gain" />
  </gain>
  <!-- 
  <gain id="dummy">
   <callback name="dummy" />
  </gain>
   -->
  <!-- 
  <gain id="current_document">
   <callback name="dummy" />
  </gain>
   -->
 </gains>
 
 <decays>
  <decay id="frustration">
   <callback name="calculate_frustration">
    <argument name="maxCost" value="1000" />
    <argument name="strength" value="0" />
   </callback>
  </decay>
  <!-- <decay id="dummy"><callback name="dummy" /></decay>  -->
 </decays>
 
 <!-- All possible transitions between actions -->
 <transitions>
  <from source="query_first">
   <to target="scan_one_summary" probability="always" />
  </from>
  <from source="next_query">
   <to target="scan_one_summary" probability="always"  />
  </from>
  <from source="scan_one_summary" decay="frustration">
   <to target="read_document" probability="decide_to_read" decay-effect="-" />
   <to target="scan_one_summary" probability="skip_to_next" decay-effect="-" />
   <to target="turn_page" probability="skip_to_next_page" />
   <to target="natural_end" probability="natural_end" />
   <to target="give_up" probability="give_up" decay-effect="+" />
   <to target="next_query" probability="skip_to_next_query" />
   <to target="stop_at_max_rank" probability="change_strategy_point_reached" />
  </from>
  <from source="read_document" decay="frustration">
   <to target="scan_one_summary" probability="skip_to_next" decay-effect="-" />
   <to target="turn_page" probability="skip_to_next_page" />
   <to target="judge_as_relevant" probability="judge_as_relevant" decay-effect="-" />
   <to target="give_up" probability="give_up" decay-effect="+" />
   <to target="natural_end" probability="natural_end" />
   <to target="next_query" probability="skip_to_next_query" />
   <to target="stop_at_max_rank" probability="change_strategy_point_reached" />
  </from>
  <from source="judge_as_relevant" decay="frustration">
   <to target="scan_one_summary" probability="skip_to_next" decay-effect="-" />
   <to target="turn_page" probability="skip_to_next_page" />
   <to target="natural_end" probability="natural_end" />
   <to target="give_up" probability="give_up" decay-effect="+" />
   <to target="next_query" probability="skip_to_next_query" />
   <to target="stop_at_max_rank" probability="change_strategy_point_reached" />
  </from>
  <from source="turn_page">
   <to target="scan_one_summary" probability="always" />
  </from>
 </transitions>
 
 <!-- All probabilities are declared here -->
 <probabilities>
  <probability id="always">
   <value>1</value>
  </probability>
  <probability id="never">
   <value>0</value>
  </probability>
  <probability id="decide_to_read">
   <!-- Conditional probability -->
   <if condition="document_is_relevant" value="0.73" />
   <else value="0.4" />
  </probability>
  <probability id="skip_to_next">
   <if condition="end_of_page" value="0" />
   <!-- <else-if condition="no_more_documents" value="0" /> -->
   <!-- Calculated at run time as 1 - sum( P(t_i) ) where P(t_i) are the 
   probabilities of other possible transitions at this point. Run time
   error if cannot be calculated. -->
   <else value="*" /> 
  </probability>
  <probability id="skip_to_next_page">
   <if condition="end_of_page" negation="true" value="0" />
   <!-- <else-if condition="no_more_documents" value="0" />  -->
   <else value="*" />
  </probability>
  <probability id="skip_to_next_query">
   <if condition="change_strategy" value="1" />
   <else value="0" />
  </probability>
  <probability id="change_strategy_point_reached">
   <if condition="no_more_queries" negation="true" value="0" />
   <else-if condition="change_strategy" value="1" />
   <else value="0" />
  </probability>
  <probability id="judge_as_relevant">
   <if condition="document_is_relevant" value="0.7" />
   <else value="0.1" />
  </probability>
  <probability id="give_up">
   <value>0</value>
  </probability>
  <probability id="natural_end">
   <if condition="gain_goal_reached" value="1" />
   <else-if condition="cost_limit_reached" value="1" />
   <else-if condition="rank_limit_reached" value="1" />
   <else value="0" />
  </probability>
 </probabilities>
  
 <!-- Run-time conditions for calculating probabilities -->
 <probability-conditions>
  <probability-condition id="document_is_relevant">
   <callback name="default_current_document_is_relevant">
    <argument name="min_relevance" value="1" />
   </callback>
  </probability-condition>
  <probability-condition id="end_of_page">
   <callback name="default_current_document_is_last_on_page" />
  </probability-condition>
  <probability-condition id="no_more_documents">
   <callback name="default_current_document_is_ranked_last" />
  </probability-condition>
  <probability-condition id="no_more_queries">
   <callback name="default_current_query_is_last" />
  </probability-condition>
  <probability-condition id="gain_goal_reached">
   <callback name="default_gain_exceeded">
    <argument name="gain_limit" value="9999" />
   </callback>
  </probability-condition>
  <probability-condition id="cost_limit_reached">
   <callback name="default_cost_exceeded">
    <argument name="cost_limit" value="1000" />
   </callback>
  </probability-condition>
  <probability-condition id="rank_limit_reached">
   <callback name="default_total_rank_exceeded">
    <argument name="rank_limit" value="20" />
   </callback>
  </probability-condition>
  <probability-condition id="change_strategy">
   <callback name="default_query_rank_exceeded">
    <argument name="rank_limit" value="3" />
   </callback>
  </probability-condition>
 </probability-conditions>
   
</qsdl>
